### ISSUE TITLE
User ID validation

### ISSUE THREAD

**Issue by Theta-Dev** [gaiterjones/amazon-alexa-php-hello-world-example#1]
Why do you only accept one user id?

`// validate user id
if ($_userId != $this->__config->get('amazonUserId')) throw new \Exception('Invalid User id: ' . $userId);`

If some other user tries to invoke this skill, it throws an error. This might be useful for testing but definitely not for distributing your skill on the skill store

**Comment by gaiterjones** [comment]
Good point, I will revise that.
