### ISSUE TITLE
TimeZone trouble

### ISSUE THREAD

**Issue by standardgbg** [gaiterjones/amazon-alexa-php-hello-world-example#2]
Hello.

**Thank you very much for your work! I**ts nice to be able to use PHP instead of JS.
I ran in to trouble with the timezones. This is related to me being in Sweden.
/PAJ/Application/Amazon/AlexaRequest.php row 226.
I had to make this change: 
`if ($_now->getTimestamp() - **_strtotime("+2 hours", strtotime_**($_alexaRequestTimestamp)) > 60)`

Also a small bug is that the error message on line 227 is presented in unixtime and 24-hour. I thought i had a formatting problem at first :)
> "Exception error, timestamp validation failure.. Current time: 1491472590 vs. Timestamp: 2017-04-06T07:56:30Z"

Suggestion on row 227:
`throw new \Exception('timestamp validation failure.. Current time: ' .  date("Y-m-d\TH:i:s\Z",$_now->getTimestamp()) . ' vs. Timestamp: ' . $_alexaRequestTimestamp);`
Generates:
> Exception error, timestamp validation failure.. Current time: 2017-04-06T11:00:05Z vs. Timestamp: 2017-04-06T08:00:04Z"

**Comment by mrtomnguyen** [comment]
there's an issue with 'Alexa. open Skill Name" '. not sure what because if you do 'Alexa, ask Skill Name to search ' works fine. any ideas?

**Comment by gaiterjones** [comment]
I will change the format of the error message and look at improving the timestamp check. Thanks for pointing this out.

**Comment by gaiterjones** [comment]
I have improved the timestamp code, but not sure why you were seeing a problem as a timestamps is the number of seconds since the Unix Epoch (January 1 1970 00:00:00 GMT) and is not affected by timezones.
