### ISSUE TITLE
Issues with skill endpoint validation on certification

### ISSUE THREAD

**Issue by alex-equities** [gaiterjones/amazon-alexa-php-hello-world-example#4]
I'm trying to make my skill published but Amazon refusing for a week. Here is the reason
"Issues with skill endpoint validation
 
The skill end-point is not validating the signatures for incoming requests and is accepting requests with an incorrect certificate URL. Please make sure that your signature validation is correct.  To reject an invalid request with an invalid signature or certificate, the skill should respond with HTTP status code 400 (Bad Request) in the response."

I checked their manual page 
https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/developing-an-alexa-skill-as-a-web-service

and I don't seem to find that step done in your code.

"7. Generate a SHA-1 hash value from the full HTTPS request body to produce the derived hash value"

Please advise

**Comment by alex-equities** [comment]
in addition to your code I set a httpd code 400 to all the places validateAlexaRequest fails, but still rejected by amazon
`	private function validateAlexaRequest()
	{
		if (php_sapi_name() === 'cli') {exit;}

		//
		// Validations based on API documentation at:
		// https://developer.amazon.com/appsandservices/solutions/alexa/alexa-skills-kit/docs/developing-an-alexa-skill-as-a-web-service#Checking%20the%20Signature%20of%20the%20Request
		//

		// validate post request
		//
		if ($_SERVER['REQUEST_METHOD'] == 'GET') throw new \Exception('HTTP GET when POST was expected');

		// validate public ip address space
		//
		if (filter_var($_SERVER['REMOTE_ADDR'], FILTER_VALIDATE_IP, FILTER_FLAG_NO_PRIV_RANGE) || filter_var($_SERVER['HTTP_X_FORWARDED_FOR'], FILTER_VALIDATE_IP, FILTER_FLAG_NO_PRIV_RANGE)) {

			$_alexaRequest=$this->get('alexarequest');

			$_sessionId          = @$_alexaRequest['session']['sessionId'];
			$_applicationId      = @$_alexaRequest['session']['application']['applicationId'];
			$_userId             = @$_alexaRequest['session']['user']['userId'];
			$_requestTimestamp   = @$_alexaRequest['request']['timestamp'];

			if (!is_array($_alexaRequest)) { throw new \Exception('Invalid alexa request data.'); }

			// validate application id
			//
			if ($_applicationId != $this->__config->get('amazonSkillId')) throw new \Exception('Invalid Application id: ' . $_applicationId);

			// validate user id
			// for private skill dev
			//if ($_userId != $this->__config->get('amazonUserId')) throw new \Exception('Invalid User id: ' . $userId);

			// Determine if we need to download a new Signature Certificate Chain from Amazon
			//
			$_md5pem = md5($_SERVER['HTTP_SIGNATURECERTCHAINURL']);
			$_md5pem = $_md5pem . '.pem';

			// If we haven't received a certificate with this URL before, store it as a cached copy
			//
			if (!file_exists($this->get('amazonLogFolder').$_md5pem)) {
				file_put_contents($this->get('amazonLogFolder').$_md5pem, file_get_contents($_SERVER['HTTP_SIGNATURECERTCHAINURL']));
			}

			// Validate proper format of Amazon provided certificate chain url
			//
			$this->validateKeychainUri($_SERVER['HTTP_SIGNATURECERTCHAINURL']);

			// Validate certificate chain and signature
			//
			$_pem = file_get_contents($this->get('amazonLogFolder').$_md5pem);


			$_ssl_check = openssl_verify($this->get('alexajsonrequest'), base64_decode($_SERVER['HTTP_SIGNATURE']), $_pem);
			if ($_ssl_check != 1)
			{
				http_response_code(400);
				exit;
				throw new \Exception(openssl_error_string());
			}

			// Parse certificate
			//
			$_parsedCertificate = openssl_x509_parse($_pem);
			if (!$_parsedCertificate)
			{
				http_response_code(400);
				exit;
				throw new \Exception('x509 certificate parse failed');
			}

			// Check that the domain echo-api.amazon.com is present in the Subject Alternative Names (SANs) section of the signing certificate
			//
			if(strpos($_parsedCertificate['extensions']['subjectAltName'], $this->__config->get('amazonEchoServiceDomain')) === false)
			{
				http_response_code(400);
				exit;
				throw new \Exception('subjectAltName Check Failed');
			}

			// Check that the signing certificate has not expired (examine both the Not Before and Not After dates)
			//
			$_validFrom = $_parsedCertificate['validFrom_time_t'];
			$_validTo   = $_parsedCertificate['validTo_time_t'];

			$_now=new \DateTime();
			$_time = $_now->getTimestamp();
			if (!($_validFrom <= $_time && $_time <= $_validTo)) {
				throw new \Exception('certificate expiration check failed');
			}

			// Check the timestamp of the request and ensure it was within the past minute
			//
			$_alexaRequestTimestamp   = @$_alexaRequest['request']['timestamp'];
			if ($_now->getTimestamp() - strtotime($_alexaRequestTimestamp) > 60)
			{
				http_response_code(400);
				exit;
				throw new \Exception('timestamp validation failure.. Current time: ' . $_now->getTimestamp() . ' vs. Timestamp: ' . $_alexaRequestTimestamp);
			}
		} // request does not originate from public ip space

	}
`

**Comment by alex-equities** [comment]
It worked with recent changes. Thanks for keeping it up.

**Comment by gaiterjones** [comment]
Sorry, I hadn't noticed this issue. We did have some issues with certification but as far as I know they are resolved. I have had 3 skills certified so far using this code.
